### PR TITLE
Fix memory limitations by using urlretrieve instead of requests

### LINKED ISSUE #1: Memory issue with using requests
For MyBinder VMs, there's limited memory and with > 1GB files, there is no guarantee that the `requests` will work.

I recommend using `urllib` as it does buffering, making it usable on any VM regardless of memory limitations.

### PR DESCRIPTION
**Pull request by astrochun**
Fixes #1

### CODE REVIEW

**Comment by astrochun** [comment]
Note that I have not tested this fully since it's a large `urlretrieve`.

**Comment by jcoliver** [comment]
Indeed. I'll try it locally before merging.

**Comment by jcoliver** [comment]
Addressed in ec4990f et al.

**Comment by astrochun** [comment]
The original recommendation was to use `urllib` and not `requests` for memory caching issues.

**Comment by jcoliver** [comment]
`urllib` _is_ now used, hence the "et al."

**Pull request closed without merging**
